- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 18000 #5 hours
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: true
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skills # Corvax-Next-Skills
        skills:
        - AdvancedBuilding

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash
